twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        uploads_dir: '%uploads_dir%'
        uploads_dir_grp: '%uploads_dir_grp%'
when@test:
    twig:
        strict_variables: true
