version: '3'

services:
###> symfony/mailer ###
  maildev:
    image: maildev/maildev
    command: bin/maildev --hide-extensions STARTTLS
    ports:
      - "1081:1080"
      - "1025:1025"
###< symfony/mailer ###
